services:
  php:
    image: graphicresources/itpg-api-coding-task:development
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public -t docs -t test public/index.php
    environment:
      docker: "true"
      XDEBUG_MODE: "coverage"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www
    depends_on:
      - db
      - cache
    networks:
      - bridge
    env_file:
      - ./app/.env

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./opt/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotr
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - bridge

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - bridge

networks:
  bridge:
